plant_database = [
    ['Carrot', ['Onion', 'Lettuce', 'Garlic'], ['Dill'], 0.25, 2],
    ['Onion', ['Carrot', 'Lettuce', 'Beet'], ['Cucumber', 'Broccoli'], 1, 2.5],
    ['Radish', ['Cucumber', 'Lettuce', 'Spinach'], [], 0.5, 1.5],
    ['Potato', ['Onion', 'Cabbage', 'Marigold'], ['Tomato', 'Cucumber', 'Broccoli'], 1, 2.5],
    ['Tomato', ['Basil', 'Marigold', 'Carrot'], ['Potato', 'Cabbage'], 0.5, 3],
    ['Basil', ['Tomato', 'Bell pepper'], [], 0.25, 1.5],
    ['Lettuce', ['Carrot', 'Onion', 'Radish', 'Cucumber'], [], 0.25, 2],
    ['Bell pepper', ['Basil', 'Marigold'], [], 0.5, 2],
    ['Cucumber', ['Radish', 'Lettuce', 'Dill'], ['Potato', 'Onion'], 1, 3],
    ['Dill', ['Cabbage', 'Cucumber'], ['Carrot', 'Tomato'], 0.25, 1.5],
    ['Spinach', ['Radish', 'Garlic', 'Onion'], [], 0.5, 2],
    ['Marigold', ['Tomato', 'Bell pepper', 'Potato'], [], 0.25, 1],
    ['Cabbage', ['Potato', 'Onion', 'Garlic', 'Dill'], ['Tomato'], 0.5, 3],
    ['Eggplant', ['Basil', 'Marigold'], [], 0.5, 2.5],
    ['Beet', ['Onion', 'Garlic'], [], 1, 2],
    ['Broccoli', ['Onion', 'Garlic'], ['Potato', 'Tomato'], 0.5, 3],
    ['Garlic', ['Carrot', 'Spinach', 'Cabbage', 'Beet'], [], 1, 1.5],
]
